"""Generate the report's figures and tables directly from the model.

Solves the CFM56-7B26 design point + SLS anchors, sweeps the SLS working line,
and writes:
  paper/report/figures/*.pdf      (matplotlib, vector)
  paper/report/tables/*.tex       (autogenerated LaTeX tables, \\input'ed)
  paper/report/figures/assets.json (raw numbers, provenance)

Every number shown in the report for model results comes from this script —
no hand-copied values. Usage: uv run python scripts/make_report_assets.py
"""

import json
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import yaml

from ehmbrain.perf.cycle import (MPCFM56, anchor_converged, anchor_summary,
                                 build_problem, design_summary, solve_anchors)

REPO_ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = REPO_ROOT / 'paper' / 'report' / 'figures'
TAB_DIR = REPO_ROOT / 'paper' / 'report' / 'tables'

INK = '#212529'
BLUE = '#4263EB'
GRAY = '#868E96'
BAND = '#CED4DA'

plt.rcParams.update({
    'font.size': 9, 'font.family': 'serif', 'axes.edgecolor': GRAY,
    'axes.labelcolor': INK, 'text.color': INK, 'xtick.color': INK,
    'ytick.color': INK, 'axes.spines.top': False, 'axes.spines.right': False,
    'axes.grid': True, 'grid.color': '#E9ECEF', 'grid.linewidth': 0.6,
    'figure.dpi': 150,
})

STATIONS = [  # (SAE station, element output, label)
    ('2', 'inlet.Fl_O', 'Fan inlet'),
    ('21', 'fan.Fl_O', 'Fan exit'),
    ('25', 'duct6.Fl_O', 'HPC inlet'),
    ('3', 'hpc.Fl_O', 'HPC exit'),
    ('4', 'burner.Fl_O', 'Burner exit'),
    ('45', 'hpt.Fl_O', 'HPT exit'),
    ('5', 'lpt.Fl_O', 'LPT exit'),
]


def sweep_working_line(prob):
    """Walk the A5 point across the SLS power range, collecting (PC, Fn, WF, N1, N2, OPR)."""
    pts = []
    for pc in (0.07, 0.10, 0.15, 0.22, 0.30, 0.40, 0.55, 0.70, 0.85, 1.00):
        prob.set_val('A5_idle.PC', pc)
        prob.run_model()
        if not anchor_converged(prob, 'A5_idle', pc):
            continue
        s = anchor_summary(prob, 'A5_idle')
        pts.append({'PC': pc, **s})
    prob.set_val('A5_idle.PC', MPCFM56.OD_ANCHORS['A5_idle'])
    return pts


def fig_anchor_errors(anchors, targets):
    fig, ax = plt.subplots(figsize=(4.8, 2.6))
    names, errs, tols, gated = [], [], [], []
    for name, s in anchors.items():
        t = targets['anchors_offdesign'][name]
        names.append(name.split('_')[0])
        errs.append((s['WF_kgps'] - t['wf_kgps']['value']) / t['wf_kgps']['value'] * 100)
        tols.append(t['wf_kgps']['tol_pct'])
        gated.append(t.get('gated', True))
    x = range(len(names))
    for i, tol in enumerate(tols):
        ax.fill_between([i - 0.3, i + 0.3], -tol, tol, color=BAND, alpha=0.55, linewidth=0)
    ax.axhline(0, color=GRAY, linewidth=0.8)
    for i, (e, g) in enumerate(zip(errs, gated)):
        ax.plot(i, e, 'o', markersize=7, color=BLUE if g else 'white',
                markeredgecolor=BLUE, markeredgewidth=1.4, zorder=3)
        ax.annotate(f'{e:+.1f} %', (i, e), textcoords='offset points',
                    xytext=(10, 2), fontsize=8)
    ax.set_xticks(list(x), ['Takeoff\n(100 %)', 'Climb-out\n(85 %)',
                            'Approach\n(30 %)', 'Idle\n(7 %)'])
    ax.set_ylabel('Fuel-flow error vs. EEDB [%]')
    ax.set_ylim(-8, 13)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'anchor_errors.pdf')
    plt.close(fig)


def fig_working_line(sweep, targets):
    fig, ax = plt.subplots(figsize=(4.8, 3.0))
    fn = [p['Fn_lbf'] * 4.448222 / 1000 for p in sweep]   # kN
    wf = [p['WF_kgps'] for p in sweep]
    ax.plot(fn, wf, '-', color=BLUE, linewidth=2, label='Model (SLS working line)')
    eedb_fn, eedb_wf = [], []
    for name, pc in MPCFM56.OD_ANCHORS.items():
        t = targets['anchors_offdesign'][name]
        eedb_fn.append(pc * 116.99)
        eedb_wf.append(t['wf_kgps']['value'])
    ax.plot(eedb_fn, eedb_wf, 'o', markersize=7, color='white',
            markeredgecolor=INK, markeredgewidth=1.4, label='ICAO EEDB (measured)', zorder=3)
    ax.set_xlabel('SLS net thrust [kN]')
    ax.set_ylabel('Fuel flow [kg/s]')
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'sls_working_line.pdf')
    plt.close(fig)


def fig_stations(prob):
    labels = [f'{num}' for num, _, _ in STATIONS]
    pt = [float(prob.get_val(f'DESIGN.{el}:tot:P', units='bar')[0]) for _, el, _ in STATIONS]
    tt = [float(prob.get_val(f'DESIGN.{el}:tot:T', units='degK')[0]) for _, el, _ in STATIONS]
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(4.8, 3.6), sharex=True)
    ax1.plot(labels, pt, 'o-', color=BLUE, linewidth=2, markersize=5)
    ax1.set_ylabel('$P_t$ [bar]')
    ax2.plot(labels, tt, 'o-', color=BLUE, linewidth=2, markersize=5)
    ax2.set_ylabel('$T_t$ [K]')
    ax2.set_xlabel('SAE ARP755A station')
    fig.align_ylabels()
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'design_stations.pdf')
    plt.close(fig)
    return {num: {'Pt_bar': p, 'Tt_K': t} for (num, _, _), p, t in zip(STATIONS, pt, tt)}


def tabla_anclas(anchors, targets):
    rows = []
    for name, s in anchors.items():
        t = targets['anchors_offdesign'][name]
        wf_t = t['wf_kgps']['value']
        err = (s['WF_kgps'] - wf_t) / wf_t * 100
        gate = '\\checkmark' if t.get('gated', True) else '---'
        pc = int(MPCFM56.OD_ANCHORS[name] * 100)
        rows.append(f"  {name.replace('_', ' ').title()} & {pc} & {s['Fn_lbf']*4.448222/1000:.1f} & "
                    f"{s['WF_kgps']:.3f} & {wf_t:.3f} & {err:+.2f} & "
                    f"\\num{{{t['wf_kgps']['tol_pct']}}} & {gate} \\\\")
    (TAB_DIR / 'table_anchors.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrrrrc}\n\\toprule\n"
        "Anchor & \\%$F_{00}$ & $F_n$ [kN] & $W_f$ model & $W_f$ EEDB & error [\\%] & tol. [\\%] & gated \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tabla_diseno(ds):
    items = [
        ('Net thrust $F_n$', f"\\SI{{{ds['Fn_lbf']*4.448222/1000:.2f}}}{{\\kilo\\newton}} (\\num{{{ds['Fn_lbf']:.0f}}} lbf)"),
        ('TSFC', f"\\num{{{ds['TSFC']:.4f}}} lb/(lbf$\\cdot$h)"),
        ('Bypass ratio (BPR)', f"\\num{{{ds['BPR']:.2f}}}"),
        ('Overall pressure ratio (OPR)', f"\\num{{{ds['OPR']:.2f}}}"),
        ('$T_{t4}$', f"\\SI{{{ds['T4_degR']/1.8:.0f}}}{{\\kelvin}} (\\num{{{ds['T4_degR']:.0f}}} °R)"),
        ('Inlet mass flow $W$', f"\\SI{{{ds['W_lbm_s']*0.4536:.1f}}}{{\\kilo\\gram\\per\\second}}"),
        ('Fuel--air ratio (FAR)', f"\\num{{{ds['FAR']:.4f}}}"),
        ('HPT expansion ratio', f"\\num{{{ds['HPT_PR']:.3f}}}"),
        ('LPT expansion ratio', f"\\num{{{ds['LPT_PR']:.3f}}}"),
        ('Total cooling/bleed fraction', f"\\num{{{ds['cooling_total_frac']:.3f}}}"),
    ]
    rows = [f'  {k} & {v} \\\\' for k, v in items]
    (TAB_DIR / 'table_design.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{ll}\n\\toprule\nQuantity & Value at the design point \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tabla_estaciones(stations):
    rows = [f"  {num} & {lab} & {stations[num]['Pt_bar']:.3f} & {stations[num]['Tt_K']:.1f} \\\\"
            for num, _, lab in STATIONS]
    (TAB_DIR / 'table_stations.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llrr}\n\\toprule\n"
        "Station & Location & $P_t$ [bar] & $T_t$ [K] \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def main():
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    TAB_DIR.mkdir(parents=True, exist_ok=True)
    targets = yaml.safe_load((REPO_ROOT / 'conf' / 'cfm56_7b_targets.yaml').read_text())

    print('Solving design point + anchors...')
    prob = build_problem(od=True)
    prob.set_solver_print(level=-1)
    converged = solve_anchors(prob)
    assert all(converged.values()), converged

    ds = design_summary(prob)
    anchors = {name: anchor_summary(prob, name) for name in MPCFM56.OD_ANCHORS}

    print('Sweeping the SLS working line...')
    sweep = sweep_working_line(prob)

    print('Generating figures and tables...')
    fig_anchor_errors(anchors, targets)
    fig_working_line(sweep, targets)
    stations = fig_stations(prob)
    tabla_anclas(anchors, targets)
    tabla_diseno(ds)
    tabla_estaciones(stations)

    (FIG_DIR / 'assets.json').write_text(json.dumps({
        'generated': date.today().isoformat(),
        'design_point': ds, 'anchors': anchors, 'sls_sweep': sweep,
        'stations': stations,
    }, indent=2))
    print(f'OK -> {FIG_DIR} y {TAB_DIR}')


if __name__ == '__main__':
    main()
