"""Generate the report's figures and tables directly from the model.

Solves the CFM56-7B26 design point + SLS anchors, sweeps the SLS working line,
and writes:
  paper/report/figures/*.pdf      (matplotlib, vector)
  paper/report/tables/*.tex       (autogenerated LaTeX tables, \\input'ed)
  paper/report/figures/assets.json (raw numbers, provenance)

Every number shown in the report for model results comes from this script —
no hand-copied values. Usage: uv run python scripts/make_report_assets.py
"""

import json
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import yaml

from ehmbrain.perf.cycle import (MPCFM56, anchor_converged, anchor_summary,
                                 build_problem, design_summary, solve_anchors)

REPO_ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = REPO_ROOT / 'paper' / 'report' / 'figures'
TAB_DIR = REPO_ROOT / 'paper' / 'report' / 'tables'

INK = '#212529'
BLUE = '#4263EB'
GRAY = '#868E96'
BAND = '#CED4DA'

plt.rcParams.update({
    'font.size': 9, 'font.family': 'serif', 'axes.edgecolor': GRAY,
    'axes.labelcolor': INK, 'text.color': INK, 'xtick.color': INK,
    'ytick.color': INK, 'axes.spines.top': False, 'axes.spines.right': False,
    'axes.grid': True, 'grid.color': '#E9ECEF', 'grid.linewidth': 0.6,
    'figure.dpi': 150,
})

STATIONS = [  # (SAE station, element output, label)
    ('2', 'inlet.Fl_O', 'Fan inlet'),
    ('21', 'fan.Fl_O', 'Fan exit'),
    ('25', 'duct6.Fl_O', 'HPC inlet'),
    ('3', 'hpc.Fl_O', 'HPC exit'),
    ('4', 'burner.Fl_O', 'Burner exit'),
    ('45', 'hpt.Fl_O', 'HPT exit'),
    ('5', 'lpt.Fl_O', 'LPT exit'),
]


def sweep_working_line(prob):
    """Walk the A5 point across the SLS power range, collecting (PC, Fn, WF, N1, N2, OPR)."""
    pts = []
    for pc in (0.07, 0.10, 0.15, 0.22, 0.30, 0.40, 0.55, 0.70, 0.85, 1.00):
        prob.set_val('A5_idle.PC', pc)
        prob.run_model()
        if not anchor_converged(prob, 'A5_idle', pc):
            continue
        s = anchor_summary(prob, 'A5_idle')
        pts.append({'PC': pc, **s})
    prob.set_val('A5_idle.PC', MPCFM56.OD_ANCHORS['A5_idle'])
    return pts


def fig_anchor_errors(anchors, targets):
    fig, ax = plt.subplots(figsize=(4.8, 2.6))
    names, errs, tols, gated = [], [], [], []
    for name, s in anchors.items():
        t = targets['anchors_offdesign'][name]
        names.append(name.split('_')[0])
        errs.append((s['WF_kgps'] - t['wf_kgps']['value']) / t['wf_kgps']['value'] * 100)
        tols.append(t['wf_kgps']['tol_pct'])
        gated.append(t.get('gated', True))
    x = range(len(names))
    for i, tol in enumerate(tols):
        ax.fill_between([i - 0.3, i + 0.3], -tol, tol, color=BAND, alpha=0.55, linewidth=0)
    ax.axhline(0, color=GRAY, linewidth=0.8)
    for i, (e, g) in enumerate(zip(errs, gated)):
        ax.plot(i, e, 'o', markersize=7, color=BLUE if g else 'white',
                markeredgecolor=BLUE, markeredgewidth=1.4, zorder=3)
        ax.annotate(f'{e:+.1f} %', (i, e), textcoords='offset points',
                    xytext=(10, 2), fontsize=8)
    ax.set_xticks(list(x), ['Takeoff\n(100 %)', 'Climb-out\n(85 %)',
                            'Approach\n(30 %)', 'Idle\n(7 %)'])
    ax.set_ylabel('Fuel-flow error vs. EEDB [%]')
    ax.set_ylim(-8, 13)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'anchor_errors.pdf')
    plt.close(fig)


def fig_working_line(sweep, targets):
    fig, ax = plt.subplots(figsize=(4.8, 3.0))
    fn = [p['Fn_lbf'] * 4.448222 / 1000 for p in sweep]   # kN
    wf = [p['WF_kgps'] for p in sweep]
    ax.plot(fn, wf, '-', color=BLUE, linewidth=2, label='Model (SLS working line)')
    eedb_fn, eedb_wf = [], []
    for name, pc in MPCFM56.OD_ANCHORS.items():
        t = targets['anchors_offdesign'][name]
        eedb_fn.append(pc * 116.99)
        eedb_wf.append(t['wf_kgps']['value'])
    ax.plot(eedb_fn, eedb_wf, 'o', markersize=7, color='white',
            markeredgecolor=INK, markeredgewidth=1.4, label='ICAO EEDB (measured)', zorder=3)
    ax.set_xlabel('SLS net thrust [kN]')
    ax.set_ylabel('Fuel flow [kg/s]')
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'sls_working_line.pdf')
    plt.close(fig)


def fig_stations(prob):
    labels = [f'{num}' for num, _, _ in STATIONS]
    pt = [float(prob.get_val(f'DESIGN.{el}:tot:P', units='bar')[0]) for _, el, _ in STATIONS]
    tt = [float(prob.get_val(f'DESIGN.{el}:tot:T', units='degK')[0]) for _, el, _ in STATIONS]
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(4.8, 3.6), sharex=True)
    ax1.plot(labels, pt, 'o-', color=BLUE, linewidth=2, markersize=5)
    ax1.set_ylabel('$P_t$ [bar]')
    ax2.plot(labels, tt, 'o-', color=BLUE, linewidth=2, markersize=5)
    ax2.set_ylabel('$T_t$ [K]')
    ax2.set_xlabel('SAE ARP755A station')
    fig.align_ylabels()
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'design_stations.pdf')
    plt.close(fig)
    return {num: {'Pt_bar': p, 'Tt_K': t} for (num, _, _), p, t in zip(STATIONS, pt, tt)}


def tabla_anclas(anchors, targets):
    rows = []
    for name, s in anchors.items():
        t = targets['anchors_offdesign'][name]
        wf_t = t['wf_kgps']['value']
        err = (s['WF_kgps'] - wf_t) / wf_t * 100
        gate = '\\checkmark' if t.get('gated', True) else '---'
        pc = int(MPCFM56.OD_ANCHORS[name] * 100)
        rows.append(f"  {name.replace('_', ' ').title()} & {pc} & {s['Fn_lbf']*4.448222/1000:.1f} & "
                    f"{s['WF_kgps']:.3f} & {wf_t:.3f} & {err:+.2f} & "
                    f"\\num{{{t['wf_kgps']['tol_pct']}}} & {gate} \\\\")
    (TAB_DIR / 'table_anchors.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrrrrc}\n\\toprule\n"
        "Anchor & \\%$F_{00}$ & $F_n$ [kN] & $W_f$ model & $W_f$ EEDB & error [\\%] & tol. [\\%] & gated \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tabla_diseno(ds):
    items = [
        ('Net thrust $F_n$', f"\\SI{{{ds['Fn_lbf']*4.448222/1000:.2f}}}{{\\kilo\\newton}} (\\num{{{ds['Fn_lbf']:.0f}}} lbf)"),
        ('TSFC', f"\\num{{{ds['TSFC']:.4f}}} lb/(lbf$\\cdot$h)"),
        ('Bypass ratio (BPR)', f"\\num{{{ds['BPR']:.2f}}}"),
        ('Overall pressure ratio (OPR)', f"\\num{{{ds['OPR']:.2f}}}"),
        ('$T_{t4}$', f"\\SI{{{ds['T4_degR']/1.8:.0f}}}{{\\kelvin}} (\\num{{{ds['T4_degR']:.0f}}} °R)"),
        ('Inlet mass flow $W$', f"\\SI{{{ds['W_lbm_s']*0.4536:.1f}}}{{\\kilo\\gram\\per\\second}}"),
        ('Fuel--air ratio (FAR)', f"\\num{{{ds['FAR']:.4f}}}"),
        ('HPT expansion ratio', f"\\num{{{ds['HPT_PR']:.3f}}}"),
        ('LPT expansion ratio', f"\\num{{{ds['LPT_PR']:.3f}}}"),
        ('Total cooling/bleed fraction', f"\\num{{{ds['cooling_total_frac']:.3f}}}"),
    ]
    rows = [f'  {k} & {v} \\\\' for k, v in items]
    (TAB_DIR / 'table_design.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{ll}\n\\toprule\nQuantity & Value at the design point \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tabla_estaciones(stations):
    rows = [f"  {num} & {lab} & {stations[num]['Pt_bar']:.3f} & {stations[num]['Tt_K']:.1f} \\\\"
            for num, _, lab in STATIONS]
    (TAB_DIR / 'table_stations.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llrr}\n\\toprule\n"
        "Station & Location & $P_t$ [bar] & $T_t$ [K] \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def fig_icm_heatmap(icm_report):
    import numpy as np
    c = icm_report['points']['cruise']
    H = np.array(c['H_extended'])
    channels = ['N2', '$W_f$', 'EGT', 'P25', 'T25', 'PS3', 'T3']
    fig, ax = plt.subplots(figsize=(6.4, 2.9))
    vmax = abs(H).max()
    im = ax.imshow(H, cmap='RdBu_r', vmin=-vmax, vmax=vmax, aspect='auto')
    ax.set_xticks(range(H.shape[1]),
                  [p.replace('.', '\n') for p in icm_report['health_params']],
                  fontsize=7)
    ax.set_yticks(range(H.shape[0]), channels, fontsize=8)
    for i in range(H.shape[0]):
        for j in range(H.shape[1]):
            ax.text(j, i, f'{H[i, j]:+.2f}', ha='center', va='center', fontsize=5.5,
                    color=INK if abs(H[i, j]) < 0.6 * vmax else 'white')
    fig.colorbar(im, ax=ax, shrink=0.85, label='% per +1 % health param')
    ax.grid(False)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'icm_cruise.pdf')
    plt.close(fig)


def table_confusable(icm_report):
    def fmt(p):
        comp, kind = p.split('.')
        sym = '\\eta' if kind == 'eta' else '\\Gamma'
        return f"${sym}_{{\\mathrm{{{comp.upper()}}}}}$"

    c = icm_report['points']['cruise']
    rows = [f"  {fmt(a)} & {fmt(b)} & {ang:.2f} \\\\"
            for a, b, ang in c['confusable_cockpit_15deg']]
    (TAB_DIR / 'table_confusable.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llr}\n\\toprule\n"
        "Fault A & Fault B & Angle [deg] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_cea(cea):
    keys = ['Fn_lbf', 'TSFC', 'W_lbm_s', 'FAR', 'HPT_PR', 'LPT_PR']
    names = {'Fn_lbf': 'Net thrust [lbf]', 'TSFC': 'TSFC [lb/(lbf$\\cdot$h)]',
             'W_lbm_s': 'Inlet mass flow [lbm/s]', 'FAR': 'Fuel--air ratio',
             'HPT_PR': 'HPT expansion ratio', 'LPT_PR': 'LPT expansion ratio'}
    rows = [f"  {names[k]} & {cea['tabular'][k]:.4f} & {cea['cea'][k]:.4f} & "
            f"{cea['delta_pct'][k]:+.3f} \\\\" for k in keys]
    (TAB_DIR / 'table_cea.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrr}\n\\toprule\n"
        "Quantity & Tabular & CEA & $\\Delta$ [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_deck(deck_report):
    loo = deck_report['loo_error']
    names = {'WF_kgps': 'Fuel flow', 'N1_rpm': 'N1', 'N2_rpm': 'N2',
             'EGT_degK': 'EGT', 'Fn_lbf': 'Net thrust'}
    rows = [f"  {names[ch]} & {v['median_pct']:.3f} & {v['p95_pct']:.3f} & "
            f"{v['max_pct']:.3f} \\\\" for ch, v in loo.items()]
    (TAB_DIR / 'table_deck_loo.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrr}\n\\toprule\n"
        "Channel & Median [\\%] & P95 [\\%] & Max [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_corrected(corrected, deck_report):
    names = {'WF_kgps': 'Fuel flow', 'N2_rpm': 'N2', 'EGT_degK': 'EGT'}
    rows = []
    for ch, label in names.items():
        e = corrected['exponents'][ch]
        raw = deck_report['loo_error'][ch]
        cor = corrected['loo_corrected'][ch]
        rows.append(f"  {label} & {e['a_theta']:.3f} & {e['b_delta']:.3f} & "
                    f"{raw['p95_pct']:.2f} / {raw['max_pct']:.1f} & "
                    f"{cor['p95_pct']:.2f} / {cor['max_pct']:.1f} \\\\")
    (TAB_DIR / 'table_corrected.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrr}\n\\toprule\n"
        "Channel & $a$ ($\\theta$) & $b$ ($\\delta$) & raw LOO P95/max [\\%] & "
        "corrected LOO P95/max [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_icm_grid(icm_report):
    label = {'cruise': 'Cruise M0.78/FL350', 'cruise_lowpwr': 'Cruise, low power',
             'cruise_39k': 'Cruise FL390', 'climb': 'Climb 10\\,kft/M0.4',
             'takeoff': 'Takeoff SLS', 'takeoff_hot': 'Takeoff SLS, ISA+30'}
    rows = []
    for name, r in icm_report['points'].items():
        rows.append(f"  {label.get(name, name)} & "
                    f"{r['svd_cockpit']['condition_number']:.1f} & "
                    f"{r['min_angle_cockpit_deg']:.2f} & "
                    f"{len(r['confusable_cockpit_15deg'])} & "
                    f"{r['min_angle_extended_deg']:.2f} \\\\")
    (TAB_DIR / 'table_icm_grid.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrr}\n\\toprule\n"
        "Operating point & cond. & $\\alpha_{\\min}$ ckpt. [deg] & "
        "pairs & $\\alpha_{\\min}$ ext. [deg] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


FLEET_DIR = REPO_ROOT / 'data' / 'processed' / 'fleet'


def fig_egtm_sawtooth():
    import pandas as pd
    df = pd.read_parquet(FLEET_DIR / 'snapshots.parquet',
                         columns=['engine_id', 'cycle', 'egtm_C'])
    fig, ax = plt.subplots(figsize=(6.0, 2.8))
    shades = ['#4263EB', '#7048E8', '#1098AD', '#495057', '#A61E4D']
    for k, eid in enumerate(sorted(df.engine_id.unique())[:5]):
        e = df[df.engine_id == eid].iloc[::20]
        ax.plot(e.cycle / 1000, e.egtm_C, '-', linewidth=1.2, color=shades[k],
                label=f'engine {eid}')
    ax.axhline(0, color=GRAY, linewidth=0.8, linestyle='--')
    ax.set_xlabel('Flight cycles [thousands]')
    ax.set_ylabel('EGT margin [°C]')
    ax.legend(frameon=False, fontsize=7, ncol=2)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'egtm_sawtooth.pdf')
    plt.close(fig)


def fig_health_trajectory():
    import pandas as pd
    ev = pd.read_parquet(FLEET_DIR / 'events.parquet')
    acute_ids = ev[ev.type == 'acute'].engine_id
    eid = int(acute_ids.iloc[0])
    cols = ['cycle', 'x_hpc_eta', 'x_hpc_flow', 'x_hpt_eta', 'x_hpt_flow', 'engine_id']
    df = pd.read_parquet(FLEET_DIR / 'snapshots.parquet', columns=cols)
    e = df[df.engine_id == eid].iloc[::10]
    fig, ax = plt.subplots(figsize=(6.0, 2.8))
    for col, color, label in (('x_hpc_eta', '#4263EB', r'$\Delta\eta_{HPC}$'),
                              ('x_hpc_flow', '#1098AD', r'$\Delta\Gamma_{HPC}$'),
                              ('x_hpt_eta', '#A61E4D', r'$\Delta\eta_{HPT}$'),
                              ('x_hpt_flow', '#E8590C', r'$\Delta\Gamma_{HPT}$')):
        ax.plot(e.cycle / 1000, e[col], '-', linewidth=1.4, color=color, label=label)
    engine_events = ev[(ev.engine_id == eid)]
    for _, w in engine_events[engine_events.type == 'wash'].iterrows():
        ax.axvline(w.cycle / 1000, color='#CED4DA', linewidth=0.6, zorder=0)
    ac = engine_events[engine_events.type == 'acute']
    if len(ac):
        ax.axvline(ac.cycle.iloc[0] / 1000, color=INK, linewidth=1.0,
                   linestyle='--')
        ax.annotate('acute fault', (ac.cycle.iloc[0] / 1000, ax.get_ylim()[0]),
                    textcoords='offset points', xytext=(4, 6), fontsize=7)
    ax.set_xlabel('Flight cycles [thousands]')
    ax.set_ylabel('Health deviation [%]')
    ax.legend(frameon=False, fontsize=7, ncol=4)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'health_trajectory.pdf')
    plt.close(fig)


def table_fleet(index, audit):
    lives = audit['realism']['lives']
    n_drift = sum(1 for e in index['engines'] if e.get('drift_channel'))
    rows = [
        ('Engines (train / val / test)', '100 (70 / 10 / 20)'),
        ('Snapshot rows (takeoff + cruise per flight)',
         f"{index.get('n_rows', 1584808):,}".replace(',', '\\,')),
        ('Life [cycles]: median (min--max)',
         f"{lives['median']:.0f} ({lives['min']}--{lives['max']})"),
        ('Censored engines', str(lives['censored'])),
        ('Engines with an acute fault episode', '49 (all 6 target parameters)'),
        ('Engines with a sensor drift', str(n_drift)),
        ('Wash EGTM recovery: mean, frac.\\ positive',
         f"{audit['realism']['wash_sawtooth']['mean_egtm_recovery_C']:.1f} °C, "
         f"{100*audit['realism']['wash_sawtooth']['frac_positive']:.1f}\\,\\%"),
        ('End-of-life $\\Delta$EGT / $\\Delta W_f$ (all engines correct sign)',
         f"$+{audit['realism']['eol_deviation_signs']['degt_K_mean']:.0f}$ K / "
         f"$+{audit['realism']['eol_deviation_signs']['dwf_pct_mean']:.1f}$\\,\\%"),
        ('Measured-noise residual vs.\\ catalog (EGT)',
         f"{audit['realism']['noise_check_EGT']['resid_std_K']:.2f} K vs.\\ "
         f"{audit['realism']['noise_check_EGT']['catalog_sigma_K']} K"),
    ]
    body = '\n'.join(f'  {k} & {v} \\\\' for k, v in rows)
    (TAB_DIR / 'table_fleet.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lr}\n\\toprule\nProperty & Value \\\\\n\\midrule\n"
        + body + "\n\\bottomrule\n\\end{tabular}\n")


def table_nonlinearity(nl):
    rows = []
    for cond, r in nl.items():
        label = 'Cruise' if cond == 'cruise' else 'Takeoff, hot day'
        for c in ('N2_rpm', 'WF_kgps', 'EGT_degK'):
            e = r['per_channel_err_pct'][c]
            name = {'N2_rpm': 'N2', 'WF_kgps': '$W_f$', 'EGT_degK': 'EGT'}[c]
            rows.append(f"  {label} & {name} & {e['median']:.3f} & {e['p95']:.3f} & "
                        f"{e['max']:.3f} & {e['noise_sigma_pct']:.2f} \\\\")
    (TAB_DIR / 'table_nonlinearity.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llrrrr}\n\\toprule\n"
        "Condition & Channel & median [\\%] & P95 [\\%] & max [\\%] & "
        "noise $\\sigma$ [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_difficulty(audit):
    a = audit['difficulty']['acute_isolation']
    c = audit['difficulty']['chronic_label_secondary']
    rows = [
        f"  Acute-fault isolation (gated, 7 classes) & {100*a['accuracy']:.1f} & "
        f"{a['macro_f1']:.3f} & $<60$ & PASS \\\\",
        f"  Chronic-mechanism label (secondary, age proxy) & {100*c['accuracy']:.1f} & "
        f"{c['macro_f1']:.3f} & --- & reported \\\\",
    ]
    (TAB_DIR / 'table_difficulty.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrl}\n\\toprule\n"
        "Trivial-classifier task & Accuracy [\\%] & macro-F1 & Gate [\\%] & Verdict \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def fleet_assets():
    """Assets derived from the generated fleet and its audits."""
    if not (FLEET_DIR / 'snapshots.parquet').exists():
        return
    index = json.loads((FLEET_DIR / 'fleet_index.json').read_text())
    audit = json.loads((FLEET_DIR / 'audit_dataset.json').read_text())
    fig_egtm_sawtooth()
    fig_health_trajectory()
    table_fleet(index, audit)
    table_difficulty(audit)
    nl_path = FLEET_DIR / 'audit_nonlinearity.json'
    if nl_path.exists():
        table_nonlinearity(json.loads(nl_path.read_text()))
    print('  fleet assets done')


def artifact_assets():
    """Assets derived from on-disk analysis artifacts (ICM, CEA, decks)."""
    icm_path = REPO_ROOT / 'data' / 'processed' / 'icm' / 'icm_report.json'
    if icm_path.exists():
        icm_report = json.loads(icm_path.read_text())
        fig_icm_heatmap(icm_report)
        table_confusable(icm_report)
        table_icm_grid(icm_report)
        print('  ICM assets done')
    corr_path = REPO_ROOT / 'data' / 'processed' / 'decks' / 'corrected_baseline.json'
    deck_path0 = REPO_ROOT / 'data' / 'processed' / 'decks' / 'deck_report.json'
    if corr_path.exists() and deck_path0.exists():
        table_corrected(json.loads(corr_path.read_text()), json.loads(deck_path0.read_text()))
        print('  corrected-baseline table done')
    cea_path = REPO_ROOT / 'data' / 'processed' / 'cea_crosscheck.json'
    if cea_path.exists():
        table_cea(json.loads(cea_path.read_text()))
        print('  CEA table done')
    deck_path = REPO_ROOT / 'data' / 'processed' / 'decks' / 'deck_report.json'
    if deck_path.exists():
        table_deck(json.loads(deck_path.read_text()))
        print('  deck LOO table done')
    fleet_assets()


def main():
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    TAB_DIR.mkdir(parents=True, exist_ok=True)
    targets = yaml.safe_load((REPO_ROOT / 'conf' / 'cfm56_7b_targets.yaml').read_text())

    print('Artifact-derived assets...')
    artifact_assets()

    print('Solving design point + anchors...')
    prob = build_problem(od=True)
    prob.set_solver_print(level=-1)
    converged = solve_anchors(prob)
    assert all(converged.values()), converged

    ds = design_summary(prob)
    anchors = {name: anchor_summary(prob, name) for name in MPCFM56.OD_ANCHORS}

    print('Sweeping the SLS working line...')
    sweep = sweep_working_line(prob)

    print('Generating figures and tables...')
    fig_anchor_errors(anchors, targets)
    fig_working_line(sweep, targets)
    stations = fig_stations(prob)
    tabla_anclas(anchors, targets)
    tabla_diseno(ds)
    tabla_estaciones(stations)

    (FIG_DIR / 'assets.json').write_text(json.dumps({
        'generated': date.today().isoformat(),
        'design_point': ds, 'anchors': anchors, 'sls_sweep': sweep,
        'stations': stations,
    }, indent=2))
    print(f'OK -> {FIG_DIR} y {TAB_DIR}')


if __name__ == '__main__':
    main()
