"""Generate the report's figures and tables directly from the model.

Solves the CFM56-7B26 design point + SLS anchors, sweeps the SLS working line,
and writes:
  paper/report/figures/*.pdf      (matplotlib, vector)
  paper/report/tables/*.tex       (autogenerated LaTeX tables, \\input'ed)
  paper/report/figures/assets.json (raw numbers, provenance)

Every number shown in the report for model results comes from this script —
no hand-copied values. Usage: uv run python scripts/make_report_assets.py
"""

import json
from datetime import date
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import yaml

from ehmbrain.perf.cycle import (MPCFM56, anchor_converged, anchor_summary,
                                 build_problem, design_summary, solve_anchors)

REPO_ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = REPO_ROOT / 'paper' / 'report' / 'figures'
TAB_DIR = REPO_ROOT / 'paper' / 'report' / 'tables'

INK = '#212529'
BLUE = '#4263EB'
GRAY = '#868E96'
BAND = '#CED4DA'

plt.rcParams.update({
    'font.size': 9, 'font.family': 'serif', 'axes.edgecolor': GRAY,
    'axes.labelcolor': INK, 'text.color': INK, 'xtick.color': INK,
    'ytick.color': INK, 'axes.spines.top': False, 'axes.spines.right': False,
    'axes.grid': True, 'grid.color': '#E9ECEF', 'grid.linewidth': 0.6,
    'figure.dpi': 150,
})

STATIONS = [  # (SAE station, element output, label)
    ('2', 'inlet.Fl_O', 'Fan inlet'),
    ('21', 'fan.Fl_O', 'Fan exit'),
    ('25', 'duct6.Fl_O', 'HPC inlet'),
    ('3', 'hpc.Fl_O', 'HPC exit'),
    ('4', 'burner.Fl_O', 'Burner exit'),
    ('45', 'hpt.Fl_O', 'HPT exit'),
    ('5', 'lpt.Fl_O', 'LPT exit'),
]


def sweep_working_line(prob):
    """Walk the A5 point across the SLS power range, collecting (PC, Fn, WF, N1, N2, OPR)."""
    pts = []
    for pc in (0.07, 0.10, 0.15, 0.22, 0.30, 0.40, 0.55, 0.70, 0.85, 1.00):
        prob.set_val('A5_idle.PC', pc)
        prob.run_model()
        if not anchor_converged(prob, 'A5_idle', pc):
            continue
        s = anchor_summary(prob, 'A5_idle')
        pts.append({'PC': pc, **s})
    prob.set_val('A5_idle.PC', MPCFM56.OD_ANCHORS['A5_idle'])
    return pts


def fig_anchor_errors(anchors, targets):
    fig, ax = plt.subplots(figsize=(4.8, 2.6))
    names, errs, tols, gated = [], [], [], []
    for name, s in anchors.items():
        t = targets['anchors_offdesign'][name]
        names.append(name.split('_')[0])
        errs.append((s['WF_kgps'] - t['wf_kgps']['value']) / t['wf_kgps']['value'] * 100)
        tols.append(t['wf_kgps']['tol_pct'])
        gated.append(t.get('gated', True))
    x = range(len(names))
    for i, tol in enumerate(tols):
        ax.fill_between([i - 0.3, i + 0.3], -tol, tol, color=BAND, alpha=0.55, linewidth=0)
    ax.axhline(0, color=GRAY, linewidth=0.8)
    for i, (e, g) in enumerate(zip(errs, gated)):
        ax.plot(i, e, 'o', markersize=7, color=BLUE if g else 'white',
                markeredgecolor=BLUE, markeredgewidth=1.4, zorder=3)
        ax.annotate(f'{e:+.1f} %', (i, e), textcoords='offset points',
                    xytext=(10, 2), fontsize=8)
    ax.set_xticks(list(x), ['Takeoff\n(100 %)', 'Climb-out\n(85 %)',
                            'Approach\n(30 %)', 'Idle\n(7 %)'])
    ax.set_ylabel('Fuel-flow error vs. EEDB [%]')
    ax.set_ylim(-8, 13)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'anchor_errors.pdf')
    plt.close(fig)


def fig_working_line(sweep, targets):
    fig, ax = plt.subplots(figsize=(4.8, 3.0))
    fn = [p['Fn_lbf'] * 4.448222 / 1000 for p in sweep]   # kN
    wf = [p['WF_kgps'] for p in sweep]
    ax.plot(fn, wf, '-', color=BLUE, linewidth=2, label='Model (SLS working line)')
    eedb_fn, eedb_wf = [], []
    for name, pc in MPCFM56.OD_ANCHORS.items():
        t = targets['anchors_offdesign'][name]
        eedb_fn.append(pc * 116.99)
        eedb_wf.append(t['wf_kgps']['value'])
    ax.plot(eedb_fn, eedb_wf, 'o', markersize=7, color='white',
            markeredgecolor=INK, markeredgewidth=1.4, label='ICAO EEDB (measured)', zorder=3)
    ax.set_xlabel('SLS net thrust [kN]')
    ax.set_ylabel('Fuel flow [kg/s]')
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'sls_working_line.pdf')
    plt.close(fig)


def fig_stations(prob):
    labels = [f'{num}' for num, _, _ in STATIONS]
    pt = [float(prob.get_val(f'DESIGN.{el}:tot:P', units='bar')[0]) for _, el, _ in STATIONS]
    tt = [float(prob.get_val(f'DESIGN.{el}:tot:T', units='degK')[0]) for _, el, _ in STATIONS]
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(4.8, 3.6), sharex=True)
    ax1.plot(labels, pt, 'o-', color=BLUE, linewidth=2, markersize=5)
    ax1.set_ylabel('$P_t$ [bar]')
    ax2.plot(labels, tt, 'o-', color=BLUE, linewidth=2, markersize=5)
    ax2.set_ylabel('$T_t$ [K]')
    ax2.set_xlabel('SAE ARP755A station')
    fig.align_ylabels()
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'design_stations.pdf')
    plt.close(fig)
    return {num: {'Pt_bar': p, 'Tt_K': t} for (num, _, _), p, t in zip(STATIONS, pt, tt)}


def tabla_anclas(anchors, targets):
    rows = []
    for name, s in anchors.items():
        t = targets['anchors_offdesign'][name]
        wf_t = t['wf_kgps']['value']
        err = (s['WF_kgps'] - wf_t) / wf_t * 100
        gate = '\\checkmark' if t.get('gated', True) else '---'
        pc = int(MPCFM56.OD_ANCHORS[name] * 100)
        rows.append(f"  {name.replace('_', ' ').title()} & {pc} & {s['Fn_lbf']*4.448222/1000:.1f} & "
                    f"{s['WF_kgps']:.3f} & {wf_t:.3f} & {err:+.2f} & "
                    f"\\num{{{t['wf_kgps']['tol_pct']}}} & {gate} \\\\")
    (TAB_DIR / 'table_anchors.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrrrrc}\n\\toprule\n"
        "Anchor & \\%$F_{00}$ & $F_n$ [kN] & $W_f$ model & $W_f$ EEDB & error [\\%] & tol. [\\%] & gated \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tabla_diseno(ds):
    items = [
        ('Net thrust $F_n$', f"\\SI{{{ds['Fn_lbf']*4.448222/1000:.2f}}}{{\\kilo\\newton}} (\\num{{{ds['Fn_lbf']:.0f}}} lbf)"),
        ('TSFC', f"\\num{{{ds['TSFC']:.4f}}} lb/(lbf$\\cdot$h)"),
        ('Bypass ratio (BPR)', f"\\num{{{ds['BPR']:.2f}}}"),
        ('Overall pressure ratio (OPR)', f"\\num{{{ds['OPR']:.2f}}}"),
        ('$T_{t4}$', f"\\SI{{{ds['T4_degR']/1.8:.0f}}}{{\\kelvin}} (\\num{{{ds['T4_degR']:.0f}}} °R)"),
        ('Inlet mass flow $W$', f"\\SI{{{ds['W_lbm_s']*0.4536:.1f}}}{{\\kilo\\gram\\per\\second}}"),
        ('Fuel--air ratio (FAR)', f"\\num{{{ds['FAR']:.4f}}}"),
        ('HPT expansion ratio', f"\\num{{{ds['HPT_PR']:.3f}}}"),
        ('LPT expansion ratio', f"\\num{{{ds['LPT_PR']:.3f}}}"),
        ('Total cooling/bleed fraction', f"\\num{{{ds['cooling_total_frac']:.3f}}}"),
    ]
    rows = [f'  {k} & {v} \\\\' for k, v in items]
    (TAB_DIR / 'table_design.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{ll}\n\\toprule\nQuantity & Value at the design point \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def tabla_estaciones(stations):
    rows = [f"  {num} & {lab} & {stations[num]['Pt_bar']:.3f} & {stations[num]['Tt_K']:.1f} \\\\"
            for num, _, lab in STATIONS]
    (TAB_DIR / 'table_stations.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llrr}\n\\toprule\n"
        "Station & Location & $P_t$ [bar] & $T_t$ [K] \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def fig_icm_heatmap(icm_report):
    import numpy as np
    c = icm_report['points']['cruise']
    H = np.array(c['H_extended'])
    channels = ['N2', '$W_f$', 'EGT', 'P25', 'T25', 'PS3', 'T3']
    fig, ax = plt.subplots(figsize=(6.4, 2.9))
    vmax = abs(H).max()
    im = ax.imshow(H, cmap='RdBu_r', vmin=-vmax, vmax=vmax, aspect='auto')
    ax.set_xticks(range(H.shape[1]),
                  [p.replace('.', '\n') for p in icm_report['health_params']],
                  fontsize=7)
    ax.set_yticks(range(H.shape[0]), channels, fontsize=8)
    for i in range(H.shape[0]):
        for j in range(H.shape[1]):
            ax.text(j, i, f'{H[i, j]:+.2f}', ha='center', va='center', fontsize=5.5,
                    color=INK if abs(H[i, j]) < 0.6 * vmax else 'white')
    fig.colorbar(im, ax=ax, shrink=0.85, label='% per +1 % health param')
    ax.grid(False)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'icm_cruise.pdf')
    plt.close(fig)


def table_confusable(icm_report):
    def fmt(p):
        comp, kind = p.split('.')
        sym = '\\eta' if kind == 'eta' else '\\Gamma'
        return f"${sym}_{{\\mathrm{{{comp.upper()}}}}}$"

    c = icm_report['points']['cruise']
    rows = [f"  {fmt(a)} & {fmt(b)} & {ang:.2f} \\\\"
            for a, b, ang in c['confusable_cockpit_15deg']]
    (TAB_DIR / 'table_confusable.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llr}\n\\toprule\n"
        "Fault A & Fault B & Angle [deg] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_cea(cea):
    keys = ['Fn_lbf', 'TSFC', 'W_lbm_s', 'FAR', 'HPT_PR', 'LPT_PR']
    names = {'Fn_lbf': 'Net thrust [lbf]', 'TSFC': 'TSFC [lb/(lbf$\\cdot$h)]',
             'W_lbm_s': 'Inlet mass flow [lbm/s]', 'FAR': 'Fuel--air ratio',
             'HPT_PR': 'HPT expansion ratio', 'LPT_PR': 'LPT expansion ratio'}
    rows = [f"  {names[k]} & {cea['tabular'][k]:.4f} & {cea['cea'][k]:.4f} & "
            f"{cea['delta_pct'][k]:+.3f} \\\\" for k in keys]
    (TAB_DIR / 'table_cea.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrr}\n\\toprule\n"
        "Quantity & Tabular & CEA & $\\Delta$ [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_deck(deck_report):
    loo = deck_report['loo_error']
    names = {'WF_kgps': 'Fuel flow', 'N1_rpm': 'N1', 'N2_rpm': 'N2',
             'EGT_degK': 'EGT', 'Fn_lbf': 'Net thrust'}
    rows = [f"  {names[ch]} & {v['median_pct']:.3f} & {v['p95_pct']:.3f} & "
            f"{v['max_pct']:.3f} \\\\" for ch, v in loo.items()]
    (TAB_DIR / 'table_deck_loo.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrr}\n\\toprule\n"
        "Channel & Median [\\%] & P95 [\\%] & Max [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_corrected(corrected, deck_report):
    names = {'WF_kgps': 'Fuel flow', 'N2_rpm': 'N2', 'EGT_degK': 'EGT'}
    rows = []
    for ch, label in names.items():
        e = corrected['exponents'][ch]
        raw = deck_report['loo_error'][ch]
        cor = corrected['loo_corrected'][ch]
        rows.append(f"  {label} & {e['a_theta']:.3f} & {e['b_delta']:.3f} & "
                    f"{raw['p95_pct']:.2f} / {raw['max_pct']:.1f} & "
                    f"{cor['p95_pct']:.2f} / {cor['max_pct']:.1f} \\\\")
    (TAB_DIR / 'table_corrected.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrr}\n\\toprule\n"
        "Channel & $a$ ($\\theta$) & $b$ ($\\delta$) & raw LOO P95/max [\\%] & "
        "corrected LOO P95/max [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_icm_grid(icm_report):
    label = {'cruise': 'Cruise M0.78/FL350', 'cruise_lowpwr': 'Cruise, low power',
             'cruise_39k': 'Cruise FL390', 'climb': 'Climb 10\\,kft/M0.4',
             'takeoff': 'Takeoff SLS', 'takeoff_hot': 'Takeoff SLS, ISA+30'}
    rows = []
    for name, r in icm_report['points'].items():
        rows.append(f"  {label.get(name, name)} & "
                    f"{r['svd_cockpit']['condition_number']:.1f} & "
                    f"{r['min_angle_cockpit_deg']:.2f} & "
                    f"{len(r['confusable_cockpit_15deg'])} & "
                    f"{r['min_angle_extended_deg']:.2f} \\\\")
    (TAB_DIR / 'table_icm_grid.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrr}\n\\toprule\n"
        "Operating point & cond. & $\\alpha_{\\min}$ ckpt. [deg] & "
        "pairs & $\\alpha_{\\min}$ ext. [deg] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


FLEET_DIR = REPO_ROOT / 'data' / 'processed' / 'fleet'


def fig_egtm_sawtooth():
    import pandas as pd
    df = pd.read_parquet(FLEET_DIR / 'snapshots.parquet',
                         columns=['engine_id', 'cycle', 'egtm_C'])
    fig, ax = plt.subplots(figsize=(6.0, 2.8))
    shades = ['#4263EB', '#7048E8', '#1098AD', '#495057', '#A61E4D']
    for k, eid in enumerate(sorted(df.engine_id.unique())[:5]):
        e = df[df.engine_id == eid].iloc[::20]
        ax.plot(e.cycle / 1000, e.egtm_C, '-', linewidth=1.2, color=shades[k],
                label=f'engine {eid}')
    ax.axhline(0, color=GRAY, linewidth=0.8, linestyle='--')
    ax.set_xlabel('Flight cycles [thousands]')
    ax.set_ylabel('EGT margin [°C]')
    ax.legend(frameon=False, fontsize=7, ncol=2)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'egtm_sawtooth.pdf')
    plt.close(fig)


def fig_health_trajectory():
    import pandas as pd
    ev = pd.read_parquet(FLEET_DIR / 'events.parquet')
    acute_ids = ev[ev.type == 'acute'].engine_id
    eid = int(acute_ids.iloc[0])
    cols = ['cycle', 'x_hpc_eta', 'x_hpc_flow', 'x_hpt_eta', 'x_hpt_flow', 'engine_id']
    df = pd.read_parquet(FLEET_DIR / 'snapshots.parquet', columns=cols)
    e = df[df.engine_id == eid].iloc[::10]
    fig, ax = plt.subplots(figsize=(6.0, 2.8))
    for col, color, label in (('x_hpc_eta', '#4263EB', r'$\Delta\eta_{HPC}$'),
                              ('x_hpc_flow', '#1098AD', r'$\Delta\Gamma_{HPC}$'),
                              ('x_hpt_eta', '#A61E4D', r'$\Delta\eta_{HPT}$'),
                              ('x_hpt_flow', '#E8590C', r'$\Delta\Gamma_{HPT}$')):
        ax.plot(e.cycle / 1000, e[col], '-', linewidth=1.4, color=color, label=label)
    engine_events = ev[(ev.engine_id == eid)]
    for _, w in engine_events[engine_events.type == 'wash'].iterrows():
        ax.axvline(w.cycle / 1000, color='#CED4DA', linewidth=0.6, zorder=0)
    ac = engine_events[engine_events.type == 'acute']
    if len(ac):
        ax.axvline(ac.cycle.iloc[0] / 1000, color=INK, linewidth=1.0,
                   linestyle='--')
        ax.annotate('acute fault', (ac.cycle.iloc[0] / 1000, ax.get_ylim()[0]),
                    textcoords='offset points', xytext=(4, 6), fontsize=7)
    ax.set_xlabel('Flight cycles [thousands]')
    ax.set_ylabel('Health deviation [%]')
    ax.legend(frameon=False, fontsize=7, ncol=4)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'health_trajectory.pdf')
    plt.close(fig)


def table_fleet(index, audit):
    """All values computed from artifacts (norm N4) — nothing hardcoded."""
    import pandas as pd
    lives = audit['realism']['lives']
    engines = index['engines']
    n = len(engines)
    splits = {}
    for e in engines:
        splits[e['split']] = splits.get(e['split'], 0) + 1
    n_rows = sum(e['life_cycles'] for e in engines)
    n_drift = sum(1 for e in engines if e.get('drift_channel'))
    ev = pd.read_parquet(FLEET_DIR / 'events.parquet')
    ac = ev[ev.type == 'acute']
    n_acute = ac.engine_id.nunique()
    n_episodes = len(ac)
    n_params = ac.param.nunique()
    rows = [
        ('Engines (train / val / test)',
         f"{n} ({splits.get('train', 0)} / {splits.get('val', 0)} / {splits.get('test', 0)})"),
        ('Snapshot rows (takeoff + cruise per flight)',
         f"{n_rows:,}".replace(',', '\\,')),
        ('Life [cycles]: median (min--max)',
         f"{lives['median']:.0f} ({lives['min']}--{lives['max']})"),
        ('Censored engines', str(lives['censored'])),
        ('Acute engines / episodes / fault classes',
         f"{n_acute} / {n_episodes} / {n_params}"),
        ('Engines with a sensor drift', str(n_drift)),
        ('Wash EGTM recovery: mean, frac.\\ positive',
         f"{audit['realism']['wash_sawtooth']['mean_egtm_recovery_C']:.1f} °C, "
         f"{100*audit['realism']['wash_sawtooth']['frac_positive']:.1f}\\,\\%"),
        ('End-of-life $\\Delta$EGT / $\\Delta W_f$ (all engines correct sign)',
         f"$+{audit['realism']['eol_deviation_signs']['degt_K_mean']:.0f}$ K / "
         f"$+{audit['realism']['eol_deviation_signs']['dwf_pct_mean']:.1f}$\\,\\%"),
        ('Measured-noise residual vs.\\ catalog (EGT)',
         f"{audit['realism']['noise_check_EGT']['resid_std_K']:.2f} K vs.\\ "
         f"{audit['realism']['noise_check_EGT']['catalog_sigma_K']} K"),
    ]
    body = '\n'.join(f'  {k} & {v} \\\\' for k, v in rows)
    (TAB_DIR / 'table_fleet.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lr}\n\\toprule\nProperty & Value \\\\\n\\midrule\n"
        + body + "\n\\bottomrule\n\\end{tabular}\n")


def table_nonlinearity(nl):
    rows = []
    for cond, r in nl.items():
        label = 'Cruise' if cond == 'cruise' else 'Takeoff, hot day'
        for c in ('N2_rpm', 'WF_kgps', 'EGT_degK'):
            e = r['per_channel_err_pct'][c]
            name = {'N2_rpm': 'N2', 'WF_kgps': '$W_f$', 'EGT_degK': 'EGT'}[c]
            rows.append(f"  {label} & {name} & {e['median']:.3f} & {e['p95']:.3f} & "
                        f"{e['max']:.3f} & {e['noise_sigma_pct']:.2f} \\\\")
    (TAB_DIR / 'table_nonlinearity.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llrrrr}\n\\toprule\n"
        "Condition & Channel & median [\\%] & P95 [\\%] & max [\\%] & "
        "noise $\\sigma$ [\\%] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_difficulty(audit):
    a = audit['difficulty']['acute_isolation']
    c = audit['difficulty']['chronic_label_secondary']
    rows = [
        f"  Acute-fault isolation (gated, 7 classes) & {100*a['accuracy']:.1f} & "
        f"{a['macro_f1']:.3f} & $<60$ & PASS \\\\",
        f"  Chronic-mechanism label (secondary, age proxy) & {100*c['accuracy']:.1f} & "
        f"{c['macro_f1']:.3f} & --- & reported \\\\",
    ]
    (TAB_DIR / 'table_difficulty.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrl}\n\\toprule\n"
        "Trivial-classifier task & Accuracy [\\%] & macro-F1 & Gate [\\%] & Verdict \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


TRAD_DIR = REPO_ROOT / 'data' / 'processed' / 'trad'


def fig_kf_tracking():
    """Kalman-GPA tracked health vs ground truth for one acute test engine."""
    import pandas as pd
    from ehmbrain.perf.icm import HEALTH_PARAMS
    from ehmbrain.trad.pipeline import BaselineModel, COCKPIT, kalman_gpa
    results = json.loads((TRAD_DIR / 'trad_results.json').read_text())
    cand = [r for r in results if r['split'] == 'test' and r['acute_param'] == 'hpt.eta']
    r = cand[0] if cand else next(r for r in results if r['acute_param'])
    eid = r['engine_id']
    e = pd.read_parquet(FLEET_DIR / 'snapshots.parquet',
                        filters=[('engine_id', '==', eid)]).sort_values('cycle')
    bm = BaselineModel()
    dz = bm.deviations(e[[f'cr_{c}' for c in COCKPIT]].to_numpy(float),
                       e.cr_N1_cmd.to_numpy())
    Ha, Hb, w = bm.cruise(e.cr_N1_cmd.to_numpy())[1]
    ev = pd.read_parquet(FLEET_DIR / 'events.parquet')
    washes = ev[(ev.engine_id == eid) & (ev.type == 'wash')].cycle.tolist()
    xs = kalman_gpa(dz, lambda i: Ha * (1 - w[i]) + Hb * w[i],
                    [0.07, 0.5, 0.23], q=2e-4, wash_cycles=washes)
    j = HEALTH_PARAMS.index(r['acute_param'])
    jc = HEALTH_PARAMS.index('hpc.eta')
    cyc = e.cycle.to_numpy() / 1000.0
    fig, ax = plt.subplots(figsize=(6.0, 2.8))
    ax.plot(cyc[::10], e[f'x_{r["acute_param"].replace(".", "_")}'].to_numpy()[::10],
            color=INK, linewidth=1.6, label='truth (faulted param)')
    ax.plot(cyc[::10], xs[::10, j], color='#A61E4D', linewidth=1.2,
            label='Kalman estimate (faulted param)')
    ax.plot(cyc[::10], xs[::10, jc], color='#4263EB', linewidth=1.2,
            label='Kalman estimate (confusable partner)')
    ax.axvline(r['acute_onset'] / 1000.0, color=GRAY, linestyle='--', linewidth=0.8)
    ax.set_xlabel('Flight cycles [thousands]')
    ax.set_ylabel('Health deviation [%]')
    ax.legend(frameon=False, fontsize=7)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'kf_smearing.pdf')
    plt.close(fig)
    return eid, r['acute_param']


def fig_rul_funnel():
    results = json.loads((TRAD_DIR / 'trad_results.json').read_text())
    fig, ax = plt.subplots(figsize=(5.2, 2.8))
    for r in results:
        if r['split'] != 'test':
            continue
        fr = [row['frac'] for row in r['rul'] if row['rul_pred'] is not None]
        err = [row['rul_pred'] - row['rul_true'] for row in r['rul']
               if row['rul_pred'] is not None]
        ax.plot(fr, err, 'o-', color=BLUE, alpha=0.35, linewidth=0.8, markersize=3)
    ax.axhline(0, color=INK, linewidth=0.8)
    ax.set_xticks([0.5, 0.7, 0.9], ['50 %', '70 %', '90 %'])
    ax.set_xlabel('Fraction of life at prediction time')
    ax.set_ylabel('RUL error [cycles]')
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'rul_funnel.pdf')
    plt.close(fig)


def table_trad(metrics):
    d, i, h = metrics['detection'], metrics['isolation'], metrics['health_tracking']
    rows = [
        ('Detection recall (acute episodes)', f"{d['recall']:.2f}"),
        ('Median detection delay', f"{d['median_delay_cycles']:.0f} cycles"),
        ('False-alarm engines (no acute episode)',
         f"{d['false_alarm_engines']} / {d['n_clean']}"),
        ('Isolation accuracy (detected episodes)', f"{i['accuracy']:.2f}"),
        ('Isolation accuracy, confusable subset',
         f"{i['confusable_accuracy']:.2f} (n={i['n_confusable']})"),
        ('Kalman health RMSE (median, 2nd half of life)',
         f"{h['kf_rmse_pct_median']:.2f}\\,\\%"),
        ('Smearing index (median, acute engines)',
         f"{h['smearing_index_median']:.2f}"),
    ]
    for f, lbl in (('0.5', '50\\,\\%'), ('0.7', '70\\,\\%'), ('0.9', '90\\,\\%')):
        r = metrics['rul'][f]
        rows.append((f'RUL median error at {lbl} of life',
                     f"$+{r['median_err_cycles']:.0f}$ cycles"))
    body = '\n'.join(f'  {k} & {v} \\\\' for k, v in rows)
    (TAB_DIR / 'table_trad.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lr}\n\\toprule\nMetric (test split, v0 defaults) & Value \\\\\n"
        "\\midrule\n" + body + "\n\\bottomrule\n\\end{tabular}\n")


def trad_assets():
    if not (TRAD_DIR / 'trad_metrics.json').exists():
        return
    table_trad(json.loads((TRAD_DIR / 'trad_metrics.json').read_text()))
    fig_kf_tracking()
    fig_rul_funnel()
    print('  trad assets done')


AI_DIR = REPO_ROOT / 'data' / 'processed' / 'ai'


def fig_rul_compare(trad, ai):
    fracs = ['0.5', '0.7', '0.9']
    x = np.arange(3)
    tr = [trad['rul'][f]['rmse_cycles'] for f in fracs]
    aa = [ai['rul'][f]['rmse_cycles'] for f in fracs]
    fig, ax = plt.subplots(figsize=(5.0, 2.8))
    ax.bar(x - 0.18, tr, 0.34, color='#868E96', label='Traditional (Theil-Sen EGTM)')
    ax.bar(x + 0.18, aa, 0.34, color=BLUE, label='AI (GRU)')
    for xi, v in zip(x - 0.18, tr):
        ax.annotate(f'{v:.0f}', (xi, v), ha='center', va='bottom', fontsize=7)
    for xi, v in zip(x + 0.18, aa):
        ax.annotate(f'{v:.0f}', (xi, v), ha='center', va='bottom', fontsize=7)
    ax.set_xticks(x, ['50 %', '70 %', '90 %'])
    ax.set_xlabel('Fraction of life at prediction time')
    ax.set_ylabel('RUL RMSE [cycles]')
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'rul_compare.pdf')
    plt.close(fig)


def fig_hybrid(hyb):
    import numpy as np
    fracs = [10, 25, 100]
    fig, ax = plt.subplots(figsize=(5.0, 2.8))
    for name, color in (('pure', BLUE), ('hybrid', '#A61E4D')):
        m = [hyb[f'{name}@{f}%']['rmse_cycles_mean'] for f in fracs]
        sdv = [hyb[f'{name}@{f}%']['rmse_cycles_std'] for f in fracs]
        ax.errorbar(fracs, m, yerr=sdv, marker='o', capsize=3, linewidth=1.6,
                    color=color, label=f'{name} GRU')
    ax.set_xscale('log')
    ax.set_xticks(fracs, ['10 %', '25 %', '100 %'])
    ax.set_xlabel('Fraction of training engines')
    ax.set_ylabel('RUL RMSE [cycles]')
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG_DIR / 'hybrid_ablation.pdf')
    plt.close(fig)


def table_ai(trad, ai):
    rows = []
    for f, lbl in (('0.5', '50'), ('0.7', '70'), ('0.9', '90')):
        t, a = trad['rul'][f], ai['rul'][f]
        rows.append(f"  RUL RMSE at {lbl}\,\% of life [cycles] & "
                    f"{t['rmse_cycles']:.0f} & {a['rmse_cycles']:.0f} \\\\")
        rows.append(f"  RUL median error at {lbl}\,\% [cycles] & "
                    f"{t['median_err_cycles']:+.0f} & {a['median_err_cycles']:+.0f} \\\\")
    rows.append(f"  Conformal coverage @0.9 (50/70/90\,\%) & --- & "
                f"{ai['rul']['0.5']['conformal_coverage']:.2f} / "
                f"{ai['rul']['0.7']['conformal_coverage']:.2f} / "
                f"{ai['rul']['0.9']['conformal_coverage']:.2f} \\\\")
    rows.append(f"  Conformal half-width [cycles] & --- & "
                f"{ai['rul']['0.5']['conformal_halfwidth_cycles']:.0f} \\\\")
    rows.append(f"  Detection recall / false alarms & "
                f"{trad['detection']['recall']:.2f} / "
                f"{trad['detection']['false_alarm_engines']} & "
                f"{ai['detection']['recall']:.2f} / "
                f"{ai['detection']['false_alarm_engines']} \\\\")
    rows.append(f"  Isolation accuracy (confusable) & "
                f"{trad['isolation']['accuracy']:.2f} "
                f"({trad['isolation']['confusable_accuracy']:.2f}) & "
                f"{ai['diagnosis']['accuracy']:.2f} "
                f"({ai['diagnosis']['confusable_accuracy']:.2f}) \\\\")
    (TAB_DIR / 'table_ai_vs_trad.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrr}\n\\toprule\n"
        "Metric (test split, v0 defaults) & Traditional & AI \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_compute():
    """Norm N5: compute-cost table from the benchmark artifact."""
    path = REPO_ROOT / 'data' / 'processed' / 'compute_times.json'
    if not path.exists():
        return
    d = json.loads(path.read_text())
    m = d['machine']
    order = ['design_point', 'sls_anchors', 'baseline_decks', 'corrected_baseline',
             'icm_grid', 'fleet_generation', 'audit_dataset', 'audit_nonlinearity',
             'traditional_pipeline', 'ai_suite', 'hybrid_ablation', 'pcs',
             'surrogate_data_cruise', 'surrogate_train', 'fleet_v2', 'h4_v2_hybrid',
             'l4_recoverable', 'l5_architectures', 'l7_drift', 'l9_pcs',
             'identifiability_certificate']
    rows = []
    total = 0.0
    for name in order:
        st = d['stages'].get(name)
        if not st:
            continue
        total += st['wall_s']
        dev = 'CPU+GPU' if st['gpu'] else 'CPU'
        rows.append(f"  {name.replace('_', ' ')} & \\code{{scripts/{st['script']}}} & "
                    f"{dev} & {st['wall_s']:.0f} \\\\")
    rows.append(f"  \\midrule\n  \\textbf{{Full pipeline}} & & & "
                f"\\textbf{{{total:.0f}}} \\\\")
    caption_info = (f"{m.get('chip', '?')}, {m.get('cores', '?')} cores, "
                    f"{m.get('mem_gb', '?')} GB, torch {m.get('torch', '?')} "
                    f"({m.get('gpu_backend', '?')})")
    (TAB_DIR / 'table_compute.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        f"% machine: {caption_info}\n"
        "\\begin{tabular}{llcr}\n\\toprule\n"
        "Stage & Script & Device & Wall time [s] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  compute table done')


def table_verdicts():
    path = REPO_ROOT / 'data' / 'processed' / 'f5' / 'verdicts.json'
    if not path.exists():
        return
    v = json.loads(path.read_text())
    rows = []
    h1 = v['H1']
    rows.append(
        f"  H1 (detection) & {'CONFIRMED' if h1['confirmed'] else 'refuted'} & "
        f"recall {h1['ai']['recall']:.2f} vs {h1['trad']['recall']:.2f}; "
        f"delay {h1['ai']['median_delay']:.0f} vs {h1['trad']['median_delay']:.0f} cy; "
        f"FA {h1['ai']['fa']}={h1['trad']['fa']} & {h1['p_holm']:.3f} \\\\")
    h2 = v['H2']
    rows.append(
        f"  H2 (confusable isolation) & {'confirmed' if h2['confirmed'] else 'REFUTED'} & "
        f"{h2['ai_confusable_acc']:.2f} vs {h2['trad_confusable_acc']:.2f} "
        f"(n={h2['n_confusable']}; discordant {h2['mcnemar']['b']}/{h2['mcnemar']['c']}) & "
        f"{h2['p_holm']:.2f} \\\\")
    h3 = v['H3']
    f9 = h3['per_fraction']['0.9']
    f5_ = h3['per_fraction']['0.5']
    rows.append(
        f"  H3 (RUL prognosis) & {'CONFIRMED' if h3['confirmed'] else 'refuted'} & "
        f"RMSE {f5_['ai_rmse']:.0f}/{f9['ai_rmse']:.0f} vs "
        f"{f5_['trad_rmse']:.0f}/{f9['trad_rmse']:.0f} cy (50/90\\,\\% life); "
        f"$\\delta$={h3['cliffs_delta_abs_err']:.2f} & "
        f"{h3['p_holm']:.1e} \\\\")
    h4 = v['H4']
    rows.append(
        f"  H4 (physics hybrid) & {'confirmed' if h4['confirmed'] else 'REFUTED'} & "
        f"hybrid worse at 10/25/100\\,\\% "
        f"({h4['summary']['hybrid@10%']:.0f} vs {h4['summary']['pure@10%']:.0f} cy at 10\\,\\%) & --- \\\\")
    h5 = v['H5']
    rows.append(
        f"  H5 (uncertainty) & {'CONFIRMED' if h5['confirmed'] else 'refuted'} & "
        f"coverage {h5['ai']['coverage']:.3f} vs {h5['trad']['coverage']:.3f} "
        f"(nominal 0.90); half-width {h5['ai']['halfwidth_cycles']:.0f} vs "
        f"{h5['trad']['halfwidth_cycles']:.0f} cy & --- \\\\")
    (TAB_DIR / 'table_verdicts.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{0.16\\textwidth}"
        ">{\\raggedright\\arraybackslash}p{0.15\\textwidth}"
        ">{\\raggedright\\arraybackslash}p{0.41\\textwidth}r}\n\\toprule\n"
        "Hypothesis & Verdict & Confirmatory evidence (AI vs traditional) & $p$ (Holm) \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  verdicts table done')


def f7_assets():
    """F7 tables: schedule design (recomputed from ICM npz, deterministic)
    and confirmatory verdicts (from verdicts_f7.json)."""
    icm_dir = REPO_ROOT / 'data' / 'processed' / 'icm'
    if not (icm_dir / 'icm_cruise.npz').exists():
        return
    import itertools
    COCK = ['N2_rpm', 'WF_kgps', 'EGT_degK']
    pts = ('cruise', 'cruise_lowpwr', 'cruise_39k', 'climb', 'takeoff',
           'takeoff_hot')
    H = {}
    for pt in pts:
        z = np.load(icm_dir / f'icm_{pt}.npz', allow_pickle=True)
        ch = [str(c) for c in z['channels']]
        H[pt] = z['H'][[ch.index(c) for c in COCK]]
    params = [str(p) for p in z['params']]
    idx = {p: i for i, p in enumerate(params)}

    def ang(stack, a, b):
        Hs = np.vstack([H[p] for p in stack])
        u, v = Hs[:, idx[a]], Hs[:, idx[b]]
        return float(np.degrees(np.arccos(np.clip(
            abs(u @ v) / (np.linalg.norm(u) * np.linalg.norm(v)), 0, 1))))

    base = ['takeoff', 'cruise']
    rows = [f"  today's schedule (takeoff + cruise) & "
            f"{ang(base, 'hpc.eta', 'hpt.eta'):.2f} & "
            f"{ang(base, 'hpt.eta', 'hpt.flow'):.2f} \\\\"]
    labels = {'cruise_lowpwr': 'low-power stabilized cruise',
              'cruise_39k': 'FL390 cruise', 'climb': 'climb report',
              'takeoff_hot': 'hot-day takeoff'}
    for extra in ('cruise_lowpwr', 'climb', 'cruise_39k', 'takeoff_hot'):
        st = base + [extra]
        rows.append(f"  + {labels[extra]} & "
                    f"{ang(st, 'hpc.eta', 'hpt.eta'):.2f} & "
                    f"{ang(st, 'hpt.eta', 'hpt.flow'):.2f} \\\\")
    st = base + ['cruise_lowpwr', 'takeoff_hot']
    rows.append(f"  + best pair (low-power cruise, hot-day takeoff) & "
                f"{ang(st, 'hpc.eta', 'hpt.eta'):.2f} & "
                f"{ang(st, 'hpt.eta', 'hpt.flow'):.2f} \\\\")
    (TAB_DIR / 'table_schedule.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrr}\n\\toprule\n"
        "Report schedule & $\\eta_{HPC}\\!\\sim\\!\\eta_{HPT}$ [deg] & "
        "$\\eta_{HPT}\\!\\sim\\!\\Gamma_{HPT}$ [deg] \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")

    vp = REPO_ROOT / 'data' / 'processed' / 'f7' / 'verdicts_f7.json'
    if vp.exists():
        v = json.loads(vp.read_text())
        h2, h3, h4 = (v['H7.2_fusion_beats_stacking'],
                      v['H7.3_drift_robustness'], v['H7.4_calibrated_ambiguity'])
        rows = [
            f"  H7.2$'$ fusion beats stacking & CONFIRMED & GRU {h2['gru_acc_short']:.2f} "
            f"vs WLS {h2['wls_acc_short']:.2f} ($+${h2['delta_pp']:.0f} pp); "
            f"McNemar $p \\leq 0.0096$ \\\\",
            f"  H7.3 drift robustness & REFUTED (as frozen) & WLS degraded "
            f"{h3['wls_degradation_pp']:.0f} pp (needed $\\geq 20$); GRU "
            f"{h3['gru_degradation_pp']:.0f} pp (needed $\\leq 10$); pattern present \\\\",
            f"  H7.4$'$ calibrated ambiguity & CONFIRMED & coverage "
            f"{h4['coverage_short']:.2f}; fundamental sets 3.0 $>$ other 2.0 \\\\"]
        (TAB_DIR / 'table_f7_verdicts.tex').write_text(
            "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
            "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{0.20\\textwidth}"
            ">{\\raggedright\\arraybackslash}p{0.17\\textwidth}"
            ">{\\raggedright\\arraybackslash}p{0.51\\textwidth}}\n\\toprule\n"
            "Hypothesis & Verdict & Confirmatory evidence \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f7 assets done')


def econ_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'econ' / 'impact.json'
    if not path.exists():
        return
    r = json.loads(path.read_text())
    a = r['annual_savings_usd']
    def m(x): return f"{x/1e6:.1f}"
    rows = [
        f"  p10 (conservative) & \\${m(a['p10'])}\\,M \\\\",
        f"  p50 (median) & \\${m(a['p50'])}\\,M \\\\",
        f"  p90 (optimistic) & \\${m(a['p90'])}\\,M \\\\",
        f"  per engine (p50) & \\${a['per_engine_p50']/1e3:.0f}\\,k/yr \\\\",
        f"  probability net-negative & {a['prob_net_negative']*100:.1f}\\,\\% \\\\"]
    (TAB_DIR / 'table_econ.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lr}\n\\toprule\n"
        "Annual fleet impact (100 engines) & Value \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  econ assets done')


def f10_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'f10' / 'verdicts_f10.json'
    if not path.exists():
        return
    import matplotlib.pyplot as plt
    v = json.loads(path.read_text())
    pdf = v['per_direction_full']
    order = sorted(pdf, key=lambda p: pdf[p]['cockpit'])
    INK, BLUE, RED = '#212529', '#4263EB', '#A61E4D'
    plt.rcParams.update({'font.size': 8.5, 'font.family': 'serif',
                         'axes.spines.top': False, 'axes.spines.right': False,
                         'figure.dpi': 150})
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(6.8, 2.9))
    yy = np.arange(len(order))
    ax1.barh(yy - 0.2, [pdf[p]['cockpit'] for p in order], 0.4, color=RED, label='cockpit')
    ax1.barh(yy + 0.2, [pdf[p]['extended'] for p in order], 0.4, color=BLUE, label='extended')
    ax1.axvline(0.7, color=INK, lw=0.6, ls='--')
    ax1.set_yticks(yy); ax1.set_yticklabels([p.replace('.', ' ') for p in order], fontsize=7)
    ax1.set_xlabel('Certified precision (CRB std) [\%]'.replace('\%', '%'))
    ax1.legend(frameon=False, fontsize=7); ax1.invert_yaxis()
    ax1.set_title('What is knowable, and what a sensor rescues', fontsize=8)
    cp = [pdf[p]['cockpit'] for p in order]
    ke = [pdf[p]['kf_err'] for p in order]
    ax2.scatter(cp, ke, color=BLUE, s=22)
    ax2.set_xlabel('Certified CRB std [\%]'.replace('\%', '%'))
    ax2.set_ylabel('Actual KF error [\%]'.replace('\%', '%'))
    ax2.set_title(f"Certificate is honest: rho={v['H10.1_honesty']['spearman_rho']:.2f}", fontsize=8)
    fig.tight_layout(); fig.savefig(FIG_DIR / 'f10_certificate.pdf'); plt.close(fig)

    h1, h2, h3 = v['H10.1_honesty'], v['H10.2_coverage'], v['H10.3_acquisition']
    rows = [
        f"  H10.1 certificate honesty & {'CONFIRMED' if h1['confirmed'] else 'refuted'} & "
        f"Spearman $\\rho={h1['spearman_rho']:.2f}$ ($p={h1['p_value']:.3f}$) between certified "
        f"precision and actual per-direction error \\\\",
        f"  H10.2 region coverage (frozen) & {'confirmed' if h2['confirmed'] else 'REFUTED'} & "
        f"true 10-dim health in the $\\chi^2$ 90\\,\\% ellipsoid at {h2['empirical_coverage']*100:.0f}\\,\\% "
        f"(band 86--94\\,\\%) \\\\",
        f"  \\quad + conformal scale (post-freeze) & restored & val-calibrated radius $\\to$ "
        f"{v['H10.2_conformal_fix']['coverage_conformal']*100:.0f}\\,\\% coverage "
        f"($\\geq$90\\,\\% guaranteed; CRB shape, conformal scale) \\\\",
        f"  H10.3 acquisition value & {'CONFIRMED' if h3['confirmed'] else 'refuted'} & "
        f"extended sensors shrink the unobservable efficiencies {h3['median_shrink']:.1f}$\\times$ "
        f"(hpc.eta {h3['cockpit_vs_extended_crb_shrink_efficiencies']['hpc.eta']:.0f}$\\times$) \\\\"]
    (TAB_DIR / 'table_f10.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{>{\\raggedright\\arraybackslash}p{0.22\\textwidth}"
        ">{\\raggedright\\arraybackslash}p{0.16\\textwidth}"
        ">{\\raggedright\\arraybackslash}p{0.50\\textwidth}}\n\\toprule\n"
        "Hypothesis & Verdict & Confirmatory evidence (single pass, test fleet) \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f10 assets done')


def f8_result_figures():
    """Conclusive F8 results as figures (from existing verdict artifacts)."""
    import matplotlib.pyplot as plt
    INK, BLUE, RED, GRAY = '#212529', '#4263EB', '#A61E4D', '#868E96'
    plt.rcParams.update({'font.size': 9, 'font.family': 'serif',
                         'axes.spines.top': False, 'axes.spines.right': False,
                         'axes.grid': True, 'axes.grid.axis': 'y', 'grid.color': '#E9ECEF',
                         'figure.dpi': 150})
    F8 = REPO_ROOT / 'data' / 'processed' / 'f8'

    # L5: architectures vs traditional (bar per life fraction)
    ap = F8 / 'arch_verdict.json'
    if ap.exists():
        v = json.loads(ap.read_text()); A = v['architectures']
        fracs = ['0.5', '0.7', '0.9']; xs = np.arange(len(fracs))
        fig, ax = plt.subplots(figsize=(5.6, 2.7))
        names = list(A); w = 0.2
        cols = [BLUE, '#1098AD', '#7048E8']
        for k, n in enumerate(names):
            ax.bar(xs + (k - 1) * w, [A[n]['rmse_by_frac'][f] for f in fracs], w,
                   label=n, color=cols[k])
        ax.axhline(v['traditional_90_rmse'], color=RED, ls='--', lw=1,
                   label='traditional @90\\%')
        ax.set_xticks(xs); ax.set_xticklabels(['50\\%', '70\\%', '90\\%'])
        ax.set_xlabel('life fraction'); ax.set_ylabel('RUL RMSE [cycles]')
        ax.legend(frameon=False, fontsize=7, ncol=2)
        fig.tight_layout(); fig.savefig(FIG_DIR / 'l5_architectures.pdf'); plt.close(fig)

    # L6: pure vs hybrid RUL by data fraction (the negative)
    hp = F8 / 'h4_v2_verdict.json'
    if hp.exists():
        r = json.loads(hp.read_text())['results']
        fr = ['0.10', '0.25', '1.00']; xs = np.arange(len(fr))
        fig, ax = plt.subplots(figsize=(5.0, 2.7))
        ax.bar(xs - 0.2, [r['pure'][f]['rmse_cycles'] for f in fr], 0.4, label='pure GRU', color=BLUE)
        ax.bar(xs + 0.2, [r['hybrid'][f]['rmse_cycles'] for f in fr], 0.4, label='+ twin-residual', color=RED)
        ax.set_xticks(xs); ax.set_xticklabels(['10\\%', '25\\%', '100\\%'])
        ax.set_xlabel('training data'); ax.set_ylabel('RUL RMSE [cycles]')
        ax.legend(frameon=False, fontsize=7)
        fig.tight_layout(); fig.savefig(FIG_DIR / 'l6_hybrid.pdf'); plt.close(fig)

    # L2: v1 linear vs v2 surrogate fidelity vs pyCycle (bar per channel)
    fp = REPO_ROOT / 'data' / 'processed' / 'fleet_v2' / 'audit_v2_fidelity.json'
    if fp.exists():
        pc = json.loads(fp.read_text())['per_channel']
        chans = list(pc); xs = np.arange(len(chans))
        fig, ax = plt.subplots(figsize=(5.0, 2.7))
        ax.bar(xs - 0.2, [pc[c]['v1_linear']['median'] for c in chans], 0.4, label='v1 linear', color=GRAY)
        ax.bar(xs + 0.2, [pc[c]['v2_surrogate']['median'] for c in chans], 0.4, label='v2 surrogate', color=BLUE)
        ax.set_xticks(xs); ax.set_xticklabels([c.replace('_', ' ') for c in chans], fontsize=7)
        ax.set_ylabel('median error vs pyCycle [\\%]')
        ax.legend(frameon=False, fontsize=7)
        fig.tight_layout(); fig.savefig(FIG_DIR / 'l2_fidelity.pdf'); plt.close(fig)
    # L1: surrogate vs linearization error per cockpit channel (same-population gate)
    sp = F8 / 'surrogate_report.json'
    if sp.exists():
        g = json.loads(sp.read_text())['gate']
        chans = list(g); xs = np.arange(len(chans))
        fig, ax = plt.subplots(figsize=(5.0, 2.7))
        ax.bar(xs - 0.2, [g[c]['linearization_same_testset']['median'] for c in chans], 0.4,
               label='linearization', color=GRAY)
        ax.bar(xs + 0.2, [g[c]['surrogate']['median'] for c in chans], 0.4,
               label='surrogate', color=BLUE)
        ax.set_xticks(xs); ax.set_xticklabels([c.replace('_', ' ') for c in chans], fontsize=8)
        ax.set_ylabel('median error vs pyCycle [\\%]')
        ax.legend(frameon=False, fontsize=7)
        fig.tight_layout(); fig.savefig(FIG_DIR / 'l1_surrogate.pdf'); plt.close(fig)
    print('  f8 result figures done')


def f8_l5_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'f8' / 'arch_verdict.json'
    if not path.exists():
        return
    v = json.loads(path.read_text())
    rows = []
    for name, d in v['architectures'].items():
        rb = d['rmse_by_frac']
        tag = '\\checkmark' if d['beats_traditional'] else '---'
        rows.append(f"  {name} & {rb['0.5']:.0f} & {rb['0.7']:.0f} & {rb['0.9']:.0f} & {tag} \\\\")
    rows.append(f"  \\midrule\n  traditional (tuned) & 3816 & 4544 & "
                f"{v['traditional_90_rmse']:.0f} & --- \\\\")
    (TAB_DIR / 'table_arch.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrc}\n\\toprule\n"
        "RUL model & 50\\,\\% & 70\\,\\% & 90\\,\\% & beats trad.\\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f8 L5 assets done')


def f8_l4_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'f8' / 'recoverable_verdict.json'
    if not path.exists():
        return
    v = json.loads(path.read_text())
    rows = [
        f"  Recoverable-fraction estimator (HistGB) & test $R^2$ & {v['test_r2']:.2f} \\\\",
        f"  & Spearman & {v['spearman']:.2f} ($p<10^{{-4}}$) \\\\",
        f"  Baseline (predict fleet mean) & test $R^2$ & 0.00 \\\\",
        f"  Ground-truth recoverable fraction & mean $\\pm$ std & "
        f"{v['truth_mean']:.2f} $\\pm$ {v['truth_std']:.2f} \\\\"]
    (TAB_DIR / 'table_recoverable.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{llr}\n\\toprule\n"
        "Quantity & Metric & Value \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f8 L4 assets done')


def f8_l9_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'f8' / 'pcs_validation.json'
    if not path.exists():
        return
    v = json.loads(path.read_text())
    sm = v['summary']
    rows = [
        f"  competent (extended sensors) & {sm['competent']['acc']:.2f} & "
        f"{sm['competent']['pcs_mean']:.3f} \\\\",
        f"  confused (cockpit) & {sm['confused']['acc']:.2f} & "
        f"{sm['confused']['pcs_mean']:.3f} \\\\",
        f"  control (shuffled labels) & {sm['control']['acc']:.2f} & "
        f"{sm['control']['pcs_mean']:.3f} \\\\"]
    (TAB_DIR / 'table_pcs.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrr}\n\\toprule\n"
        "Classifier & Isolation acc. & Mean PCS \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f8 L9 assets done')


def f8_l6_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'f8' / 'h4_v2_verdict.json'
    if not path.exists():
        return
    r = json.loads(path.read_text())['results']
    rows = []
    for f in ('0.10', '0.25', '1.00'):
        rows.append(f"  {int(float(f)*100)}\\,\\% & {r['pure'][f]['rmse_cycles']:.0f} & "
                    f"{r['hybrid'][f]['rmse_cycles']:.0f} \\\\")
    (TAB_DIR / 'table_h4v2.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrr}\n\\toprule\n"
        "Train data & Pure GRU & Hybrid (+twin-residual) \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f8 L6 assets done')


def f8_l2_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'fleet_v2' / 'audit_v2_fidelity.json'
    if not path.exists():
        return
    r = json.loads(path.read_text())['per_channel']
    rows = []
    for c, d in r.items():
        rows.append(f"  {c.replace('_', ' ')} & {d['v1_linear']['median']:.3f} & "
                    f"{d['v1_linear']['p95']:.3f} & {d['v2_surrogate']['median']:.3f} & "
                    f"{d['v2_surrogate']['p95']:.3f} & {d['improvement_factor_median']:.1f}$\\times$ \\\\")
    (TAB_DIR / 'table_v2_fidelity.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrrc}\n\\toprule\n"
        " & \\multicolumn{2}{c}{v1 linear} & \\multicolumn{2}{c}{v2 surrogate} & \\\\\n"
        "Channel & med [\\%] & P95 [\\%] & med [\\%] & P95 [\\%] & gain \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f8 L2 assets done')


def f8_assets():
    path = REPO_ROOT / 'data' / 'processed' / 'f8' / 'surrogate_report.json'
    if not path.exists():
        return
    r = json.loads(path.read_text())
    rows = []
    for chn, g in r['gate'].items():
        su, li = g['surrogate'], g['linearization_same_testset']
        rows.append(f"  {chn.replace('_', ' ')} & {su['median']:.4f} & {su['p95']:.4f} & "
                    f"{li['median']:.4f} & {li['p95']:.4f} & "
                    f"{'PASS' if g['pass'] else 'FAIL'} \\\\")
    (TAB_DIR / 'table_surrogate.tex').write_text(
        "% AUTOGENERATED by scripts/make_report_assets.py — do NOT edit by hand\n"
        "\\begin{tabular}{lrrrrc}\n\\toprule\n"
        " & \\multicolumn{2}{c}{Surrogate} & \\multicolumn{2}{c}{Linearization} & \\\\\n"
        "Channel & med [\\%] & P95 [\\%] & med [\\%] & P95 [\\%] & Gate \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print('  f8 assets done')


def ai_assets():
    trad_p = REPO_ROOT / 'data' / 'processed' / 'trad' / 'trad_metrics.json'
    ai_p = AI_DIR / 'ai_metrics.json'
    hyb_p = AI_DIR / 'hybrid_metrics.json'
    if not (trad_p.exists() and ai_p.exists()):
        return
    trad = json.loads(trad_p.read_text())
    ai = json.loads(ai_p.read_text())
    fig_rul_compare(trad, ai)
    table_ai(trad, ai)
    if hyb_p.exists():
        fig_hybrid(json.loads(hyb_p.read_text()))
    print('  ai assets done')


def fleet_assets():
    """Assets derived from the generated fleet and its audits."""
    if not (FLEET_DIR / 'snapshots.parquet').exists():
        return
    index = json.loads((FLEET_DIR / 'fleet_index.json').read_text())
    audit = json.loads((FLEET_DIR / 'audit_dataset.json').read_text())
    fig_egtm_sawtooth()
    fig_health_trajectory()
    table_fleet(index, audit)
    table_difficulty(audit)
    nl_path = FLEET_DIR / 'audit_nonlinearity.json'
    if nl_path.exists():
        table_nonlinearity(json.loads(nl_path.read_text()))
    print('  fleet assets done')


def artifact_assets():
    """Assets derived from on-disk analysis artifacts (ICM, CEA, decks)."""
    icm_path = REPO_ROOT / 'data' / 'processed' / 'icm' / 'icm_report.json'
    if icm_path.exists():
        icm_report = json.loads(icm_path.read_text())
        fig_icm_heatmap(icm_report)
        table_confusable(icm_report)
        table_icm_grid(icm_report)
        print('  ICM assets done')
    corr_path = REPO_ROOT / 'data' / 'processed' / 'decks' / 'corrected_baseline.json'
    deck_path0 = REPO_ROOT / 'data' / 'processed' / 'decks' / 'deck_report.json'
    if corr_path.exists() and deck_path0.exists():
        table_corrected(json.loads(corr_path.read_text()), json.loads(deck_path0.read_text()))
        print('  corrected-baseline table done')
    cea_path = REPO_ROOT / 'data' / 'processed' / 'cea_crosscheck.json'
    if cea_path.exists():
        table_cea(json.loads(cea_path.read_text()))
        print('  CEA table done')
    deck_path = REPO_ROOT / 'data' / 'processed' / 'decks' / 'deck_report.json'
    if deck_path.exists():
        table_deck(json.loads(deck_path.read_text()))
        print('  deck LOO table done')
    fleet_assets()
    trad_assets()
    ai_assets()
    table_compute()
    table_verdicts()
    f7_assets()
    f8_assets()
    f8_l2_assets()
    f8_l6_assets()
    f8_result_figures()
    f8_l5_assets()
    f8_l4_assets()
    f8_l9_assets()
    f10_assets()
    econ_assets()


def main():
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    TAB_DIR.mkdir(parents=True, exist_ok=True)
    targets = yaml.safe_load((REPO_ROOT / 'conf' / 'cfm56_7b_targets.yaml').read_text())

    print('Artifact-derived assets...')
    artifact_assets()

    print('Solving design point + anchors...')
    prob = build_problem(od=True)
    prob.set_solver_print(level=-1)
    converged = solve_anchors(prob)
    assert all(converged.values()), converged

    ds = design_summary(prob)
    anchors = {name: anchor_summary(prob, name) for name in MPCFM56.OD_ANCHORS}

    print('Sweeping the SLS working line...')
    sweep = sweep_working_line(prob)

    print('Generating figures and tables...')
    fig_anchor_errors(anchors, targets)
    fig_working_line(sweep, targets)
    stations = fig_stations(prob)
    tabla_anclas(anchors, targets)
    tabla_diseno(ds)
    tabla_estaciones(stations)

    (FIG_DIR / 'assets.json').write_text(json.dumps({
        'generated': date.today().isoformat(),
        'design_point': ds, 'anchors': anchors, 'sls_sweep': sweep,
        'stations': stations,
    }, indent=2))
    print(f'OK -> {FIG_DIR} y {TAB_DIR}')


if __name__ == '__main__':
    main()
